steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'scp', '--project', 'ikabu-bot', '--zone', 'global', --recurse, '$BRANCH_NAME', 'gcp-instance-name','ikabu-host']
