steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'scp', '--project', 'ikabu-bot', '--zone', 'us-west1-a',  '--recurse', '../ikabu', 'bukichi@ikabu-host:/home/$BRANCH_NAME/']
