module.exports = {
    commandNames: {
        voice_channel: 'voice_channel',
        close: 'close',
        friend_code: 'friend_code',
        wiki: 'wiki',
        kansen: 'kansen',
        timer: 'timer',
        pick: 'pick',
        voice_pick: 'vpick',
        buki: 'buki',
        show: 'show',
        help: 'help',
        ban: 'ban',
        ch_manager: 'ch_management',
        experience: 'イカ部歴',
        other_game: '別ゲー募集',
        regular: 'ナワバリ募集',
        league: 'リグマ募集',
        salmon: 'サーモンラン募集',
        private: 'プラベ募集',
    },
};
