export const commandNames = {
    vclock: 'ボイスロック',
    close: 'close',
    friend_code: 'friend_code',
    wiki: 'wiki',
    kansen: 'kansen',
    team_divider: 'チーム分け',
    timer: 'timer',
    pick: 'pick',
    voice_pick: 'vpick',
    buki: 'buki',
    show: 'show',
    help: 'help',
    ban: 'ban',
    ch_manager: 'ch_management',
    voice: 'voice',
    experience: 'イカ部歴',
    other_game: '別ゲー募集',
    regular: 'ナワバリ募集',
    league: 'リグマ募集',
    anarchy: 'バンカラ募集',
    salmon: 'サーモンラン募集',
    fesA: 'フウカ陣営',
    fesB: 'マンタロー陣営',
    fesC: 'ウツホ陣営',
    private: 'プラベ募集',
    buttonEnabler: 'ボタンを有効化する',
    voiceChannelMention: 'ボイスメンション',
    variablesSettings: '環境変数設定',
};
export const modalRecruit = {
    placeHold:
        'https://placehold.jp/22/4650bc/ffffff/150x150.png?text=%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E5%8B%9F%E9%9B%86%0A%E3%81%AA%E3%82%89%E8%A1%A8%E7%A4%BA%E5%8F%AF%E8%83%BD',
};
